# Generated by Django 2.2.7 on 2019-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('gh_link', models.URLField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(max_length=100, verbose_name='Text')),
                ('in_progress', models.BooleanField()),
            ],
        ),
    ]
