# Generated by Django 2.2.7 on 2019-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
