# Generated by Django 2.2.7 on 2019-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191110_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Text'),
        ),
    ]
