# Generated by Django 2.2.7 on 2019-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191110_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='gh_not_link',
            field=models.BooleanField(default=True),
        ),
    ]
