# Generated by Django 2.2.7 on 2019-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_gh_not_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='in_que',
            field=models.BooleanField(default=True),
        ),
    ]
